### PR TITLE
use default backend instead

### PR DESCRIPTION
**Pull request by EllaDing**
Remove StateBackendOptions to use the default state backend.

### CODE REVIEW

**Comment by KevinGG** [comment]
Is this PR still alive? Are we updating the example pipelines to default to the managed configurations?

**Comment by clmccart** [comment]
> Is this PR still alive? Are we updating the example pipelines to default to the managed configurations?

not sure. let me ping Yi

**Comment by EllaDing** [comment]
yesh it is still alive. We should remove the backend state parameter from the pipeline code, so that our backend will pick the right backend as default (which is RocksDB).

**Comment by EllaDing** [comment]
Let me add it to other pipeline code as well.

**Comment by EllaDing** [comment]
> can we add this to the other WC pipelines as well?

Updated, PTAL

**Review by clmccart — APPROVED** [review]

**Pull request merged**
